// lib/screenerTickers.ts — master ticker list for the screener
// Categorised so we can filter by type and show meaningful labels.

export interface TickerMeta {
  ticker: string;
  type: 'stock' | 'fii' | 'etf' | 'bdr';
  sector?: string;
}

export const SCREENER_TICKERS: TickerMeta[] = [
  // ── Ações ───────────────────────────────────────────────────
  { ticker: 'PETR4',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'PETR3',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'VALE3',  type: 'stock', sector: 'Mineração' },
  { ticker: 'ITUB4',  type: 'stock', sector: 'Bancos' },
  { ticker: 'BBAS3',  type: 'stock', sector: 'Bancos' },
  { ticker: 'BBDC4',  type: 'stock', sector: 'Bancos' },
  { ticker: 'BBDC3',  type: 'stock', sector: 'Bancos' },
  { ticker: 'ITSA4',  type: 'stock', sector: 'Bancos' },
  { ticker: 'SANB11', type: 'stock', sector: 'Bancos' },
  { ticker: 'BRSR6',  type: 'stock', sector: 'Bancos' },
  { ticker: 'BPAC11', type: 'stock', sector: 'Bancos' },
  { ticker: 'WEGE3',  type: 'stock', sector: 'Bens Industriais' },
  { ticker: 'ABEV3',  type: 'stock', sector: 'Bebidas' },
  { ticker: 'RENT3',  type: 'stock', sector: 'Transporte' },
  { ticker: 'PRIO3',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'EGIE3',  type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'TAEE11', type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'CPLE6',  type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'ENGI11', type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'TRPL4',  type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'CMIG4',  type: 'stock', sector: 'Energia Elétrica' },
  { ticker: 'SBSP3',  type: 'stock', sector: 'Saneamento' },
  { ticker: 'SAPR11', type: 'stock', sector: 'Saneamento' },
  { ticker: 'CSAN3',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'UGPA3',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'RAIZ4',  type: 'stock', sector: 'Petróleo & Gás' },
  { ticker: 'MGLU3',  type: 'stock', sector: 'Varejo' },
  { ticker: 'LREN3',  type: 'stock', sector: 'Varejo' },
  { ticker: 'SOMA3',  type: 'stock', sector: 'Varejo' },
  { ticker: 'RDOR3',  type: 'stock', sector: 'Saúde' },
  { ticker: 'HAPV3',  type: 'stock', sector: 'Saúde' },
  { ticker: 'FLRY3',  type: 'stock', sector: 'Saúde' },
  { ticker: 'HYPE3',  type: 'stock', sector: 'Saúde' },
  { ticker: 'SLCE3',  type: 'stock', sector: 'Agronegócio' },
  { ticker: 'AGRO3',  type: 'stock', sector: 'Agronegócio' },
  { ticker: 'SMTO3',  type: 'stock', sector: 'Agronegócio' },
  { ticker: 'CAML3',  type: 'stock', sector: 'Agronegócio' },
  { ticker: 'VIVT3',  type: 'stock', sector: 'Telecomunicações' },
  { ticker: 'TIMS3',  type: 'stock', sector: 'Telecomunicações' },
  { ticker: 'TOTVS3', type: 'stock', sector: 'Tecnologia' },
  { ticker: 'EMBR3',  type: 'stock', sector: 'Indústria' },
  { ticker: 'SUZB3',  type: 'stock', sector: 'Papel & Celulose' },
  { ticker: 'KLBN11', type: 'stock', sector: 'Papel & Celulose' },
  { ticker: 'CSNA3',  type: 'stock', sector: 'Siderurgia' },
  { ticker: 'GGBR4',  type: 'stock', sector: 'Siderurgia' },
  { ticker: 'USIM5',  type: 'stock', sector: 'Siderurgia' },
  { ticker: 'GOAU4',  type: 'stock', sector: 'Siderurgia' },
  { ticker: 'CYRE3',  type: 'stock', sector: 'Construção Civil' },
  { ticker: 'MRVE3',  type: 'stock', sector: 'Construção Civil' },
  { ticker: 'EVEN3',  type: 'stock', sector: 'Construção Civil' },
  { ticker: 'EZTC3',  type: 'stock', sector: 'Construção Civil' },
  { ticker: 'MULT3',  type: 'stock', sector: 'Shoppings' },
  { ticker: 'IGTI11', type: 'stock', sector: 'Shoppings' },
  // ── FIIs ────────────────────────────────────────────────────
  { ticker: 'MXRF11', type: 'fii', sector: 'FII Papel' },
  { ticker: 'HGLG11', type: 'fii', sector: 'FII Logística' },
  { ticker: 'XPML11', type: 'fii', sector: 'FII Shopping' },
  { ticker: 'VISC11', type: 'fii', sector: 'FII Shopping' },
  { ticker: 'KNRI11', type: 'fii', sector: 'FII Híbrido' },
  { ticker: 'BCFF11', type: 'fii', sector: 'FII FOF' },
  { ticker: 'IRDM11', type: 'fii', sector: 'FII Papel' },
  { ticker: 'RBRF11', type: 'fii', sector: 'FII FOF' },
  { ticker: 'BTLG11', type: 'fii', sector: 'FII Logística' },
  { ticker: 'HSML11', type: 'fii', sector: 'FII Shopping' },
  { ticker: 'BRCO11', type: 'fii', sector: 'FII Logística' },
  { ticker: 'HFOF11', type: 'fii', sector: 'FII FOF' },
  { ticker: 'RECR11', type: 'fii', sector: 'FII Papel' },
  { ticker: 'CPTS11', type: 'fii', sector: 'FII Papel' },
  { ticker: 'RZTR11', type: 'fii', sector: 'FII Agro' },
  // ── ETFs ────────────────────────────────────────────────────
  { ticker: 'BOVA11', type: 'etf' },
  { ticker: 'IVVB11', type: 'etf' },
  { ticker: 'SMAL11', type: 'etf' },
  { ticker: 'HASH11', type: 'etf' },
];
